print("|*****************|")
print("|    Desafio04    |")
print("|*****************|")
print("")
print("Tipo e testes de tipo")

algo = input("Digite algo: ")

print("Seu tipo é {}".format(type(algo)))
print("É numérico? {}".format(algo.isnumeric()))
print("É decimal? {}".format(algo.isdecimal()))
print("É alfabético? {}".format(algo.isalpha()))
print("É alfanumérico? {}".format(algo.isalnum()))
print("É capitalizado? {}".format(algo.isupper()))
print("É um minusculo? {}".format(algo.islower()))
print("É um digito? {}".format(algo.isdigit()))
print("É um titulo? {}".format(algo.istitle()))
print("É um identificador? {}".format(algo.isidentifier()))
print("É um exibivel? {}".format(algo.isprintable()))
print("É um espaço? {}".format(algo.isspace()))
